### ISSUE TITLE
Error creating draft release in recipe version 1.1.0

### ISSUE THREAD

**Issue by CharliePoole** [TestCentric/TestCentric.Cake.Recipe#67]
Create draft release encounters an overflow exception and fails. Problem doesn't seem to be in our script, since it can be replicated using GitReleaseManager.Commandline directly.

```
Creating release...
[FTL] Value was either too large or too small for an Int32.
GitReleaseManager.Core.Exceptions.ApiException: Value was either too large or too small for an Int32. ---> System.OverflowException: Value was either too large or too small for an Int32.
   at System.Convert.ToInt32(Int64 value)
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at Octokit.PocoJsonSerializerStrategy.DeserializeObject(Object value, Type type) in /home/runner/work/octokit.net/octokit.net/Octokit/SimpleJson.cs:line 1441   at Octokit.PocoJsonSerializerStrategy.DeserializeObject(Object value, Type type) in /home/runner/work/octokit.net/octokit.net/Octokit/SimpleJson.cs:line 1494   at Octokit.PocoJsonSerializerStrategy.DeserializeObject(Object value, Type type) in /home/runner/work/octokit.net/octokit.net/Octokit/SimpleJson.cs:line 1521   at Octokit.SimpleJson.DeserializeObject[T](String json, IJsonSerializerStrategy jsonSerializerStrategy) in /home/runner/work/octokit.net/octokit.net/Octokit/SimpleJson.cs:line 602
   at Octokit.Internal.JsonHttpPipeline.DeserializeResponse[T](IResponse response) in /home/runner/work/octokit.net/octokit.net/Octokit/Http/JsonHttpPipeline.cs:line 62
   at Octokit.Connection.<Run>d__59`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Octokit.ApiConnection.<GetPage>d__43`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Octokit.ApiConnection.<>c__DisplayClass18_0`1.<<GetAll>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Octokit.ApiPagination.<GetAllPages>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at GitReleaseManager.Core.Provider.GitHubProvider.<>c__DisplayClass10_0.<<GetIssuesAsync>b__0>d.MoveNext() in /_/src/GitReleaseManager.Core/Provider/GitHubProvider.cs:line 112
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitReleaseManager.Core.Provider.GitHubProvider.<ExecuteAsync>d__26`1.MoveNext() in /_/src/GitReleaseManager.Core/Provider/GitHubProvider.cs:line 0
   --- End of inner exception stack trace ---
   at GitReleaseManager.Core.Provider.GitHubProvider.<ExecuteAsync>d__26`1.MoveNext() in /_/src/GitReleaseManager.Core/Provider/GitHubProvider.cs:line 384
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitReleaseManager.Core.ReleaseNotes.ReleaseNotesBuilder.<GetIssuesAsync>d__17.MoveNext() in /_/src/GitReleaseManager.Core/ReleaseNotes/ReleaseNotesBuilder.cs:line 184
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitReleaseManager.Core.ReleaseNotes.ReleaseNotesBuilder.<BuildReleaseNotes>d__11.MoveNext() in /_/src/GitReleaseManager.Core/ReleaseNotes/ReleaseNotesBuilder.cs:line 48
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitReleaseManager.Core.VcsService.<CreateReleaseFromMilestoneAsync>d__9.MoveNext() in /_/src/GitReleaseManager.Core/VcsService.cs:line 55
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitReleaseManager.Core.Commands.CreateCommand.<Execute>d__3.MoveNext() in /_/src/GitReleaseManager.Core/Commands/CreateCommand.cs:line 41
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitReleaseManager.Cli.Program.<Main>d__1.MoveNext() in /_/src/GitReleaseManager.Cli/Program.cs:line 34
```

**Comment by CharliePoole** [comment]
Error was detected when trying to do the 1.2.0 release of TestCentric.InternalTrace. It was replicated doing a test draft release of TestCentric.Metadata.

For  the TestCentric.InternalTrace release, I created the draft release in the GitHub web interface and had GitHub generate the release notes. I observed that I was able to publish the release, triggering a build, which successfully added the assets but was unable to add comments to the resolved issues.

The underlying problem appears to be in some of the dependencies used by GitReleaseNanager. If that's true, this issue will be blocked until the problem is resolved. As an alternative, we could stop using GRM for draft releases and either fix or bypass the addition of comments to the resolved isssues.

We were using GRM 0.12.1 when this occured. However, temporarily upgrading to 0.16.0 did not resolve the problem.

**Comment by CharliePoole** [comment]
Further testing by doing a not-really-necessary release of TestCentric.Metadata shows that closing the milestone generates exactly the same failure. As an interim fix, I plan to...

1. Use the GitHub web UI to create draft releases and publish them
2. Do a point release of TestCentric.Cake.Recipe, which bypasses creating a draft release and doesn't attempt to close the milesone.

**Comment by CharliePoole** [comment]
Draft Release creation is bypassed in version 1.2.0
